/**
 * Builds the Cloudflare `_headers` file (Workers Static Assets) so the Cloudflare deploy serves the
 * same security headers and cache policy as nginx.conf.
 *
 * - Security headers come straight from deploy/security-headers.conf (single source of truth).
 * - Cache policy mirrors the location blocks of nginx.conf. Cloudflare joins the values of every
 *   matching rule with commas, so the Cache-Control rules below are mutually exclusive by path.
 */

const ONE_YEAR = 'public, max-age=31536000, immutable';
const ONE_WEEK = 'public, max-age=604800';
const REVALIDATE = 'no-cache';

/** Extensions nginx.conf caches for a week (non-fingerprinted static media). */
const MEDIA_EXTENSIONS = /\.(?:png|webp|svg|ico|woff2)$/i;
/** Entry points that must always be revalidated or deploys and service-worker updates never arrive. */
const REVALIDATED_PATHS = ['/index.html', '/manifest.webmanifest', '/sw.js', '/registerSW.js', '/workbox-*'];

/** `add_header Name "value" always;` lines of the nginx snippet (indented or not, quoted or bare value). */
export function parseNginxHeaders(conf: string): Array<[string, string]> {
    return Array.from(conf.matchAll(/^\s*add_header\s+(\S+)\s+(?:"([^"]*)"|([^\s;]+))/gm), m => [m[1], m[2] ?? m[3]] as [string, string]);
}

/**
 * @param nginxHeadersConf contents of deploy/security-headers.conf
 * @param publicFiles every file of `public/` (relative paths): decides which non-fingerprinted media get the weekly cache
 */
export function buildHeadersFile(nginxHeadersConf: string, publicFiles: string[]): string {
    const rule = (pattern: string, headers: Array<[string, string]>) =>
        [pattern, ...headers.map(([name, value]) => `  ${name}: ${value}`)].join('\n');

    const rules: string[] = [
        rule('/*', parseNginxHeaders(nginxHeadersConf)),
        // Vite fingerprints everything under /assets/.
        rule('/assets/*', [['Cache-Control', ONE_YEAR]]),
        ...REVALIDATED_PATHS.map(path => rule(path, [['Cache-Control', REVALIDATE]])),
        // Audio samples (wav/ogg), cached for a week.
        rule('/audio/*', [['Cache-Control', ONE_WEEK]]),
    ];

    // Images, icons and fonts that Vite copies from public/ as-is (not fingerprinted): one rule per directory
    // (or file at the root) so a rule never overlaps /assets/* or /audio/*.
    const weekly = new Set<string>();
    for (const file of publicFiles) {
        if (!MEDIA_EXTENSIONS.test(file) || file.startsWith('audio/')) continue;
        const slash = file.indexOf('/');
        weekly.add(slash === -1 ? `/${file}` : `/${file.slice(0, slash)}/*`);
    }
    for (const pattern of [...weekly].sort()) rules.push(rule(pattern, [['Cache-Control', ONE_WEEK]]));

    return `# Generated by deploy/cloudflareHeaders.ts from deploy/security-headers.conf and the cache policy of nginx.conf. Do not edit.\n${rules.join('\n\n')}\n`;
}
